/* 可扩展原创阅读数据层：主题种子可继续维护，不把文章数量写死在页面。 */
const READING_TOPICS=["adult education","workplace training","public transport","healthy sleep","urban parks","online learning","recycling","community libraries","career change","family care","local history","small businesses","weather science","digital safety","volunteering","rural services","time management","consumer choices","museum visits","food labels"];
const readingBase=[
"Many adults return to study while working. Their progress is rarely caused by one long weekend. It comes from a clear plan, short daily practice, and regular review. A learner who misses a day should not decide that the whole plan has failed. Instead, the learner can reduce the next task and begin again. Teachers often find that understanding a paragraph is more useful than memorizing an isolated list of words.",
"A useful public service is usually designed around an ordinary problem. People may need information, a safe place, or an easier way to travel. When a service is difficult to understand, even a well-funded project may help fewer people. Clear signs, patient staff, and simple explanations can make a practical difference.",
"Researchers often compare habits over time rather than judging one action. A small change may appear unimportant on one day, yet produce a visible result after several weeks. This is why many health and education programs ask people to record what they do and review the record honestly. The purpose is not to create pressure, but to find a method that can continue."
];
READINGS=READINGS.map((r,i)=>({...r,id:r.id||'starter-'+(i+1),level:r.level||'A',type:r.type||'基础过渡'}));
const qtypes=[['细节题','According to the passage, which action is most helpful?'],['主旨题','What is the passage mainly concerned with?'],['推理题','What can be inferred from the passage?'],['词义题','The word “continue” is closest in meaning to:']];
const generated=[];for(let i=0;i<100;i++){const topic=READING_TOPICS[i%READING_TOPICS.length],base=readingBase[i%readingBase.length];const text=base+' The example of '+topic+' shows the same principle. People need to notice the reason behind a decision, compare possible results, and choose a response that fits the situation. This approach is modest, but it helps readers understand information instead of relying on a familiar phrase. In an examination, the best answer is supported by the passage; an attractive answer that adds an unstated idea should be treated carefully.';generated.push({id:'gen-'+String(i+1).padStart(3,'0'),title:topic.replace(/\b\w/g,x=>x.toUpperCase()),level:i<30?'A':i<60?'C':i<100?'D':'E',type:['说明文','议论文','社会生活','科普'][i%4],text,translation:'这是一篇围绕'+topic+'的原创成考训练短文。',question:qtypes[i%4][1],questionType:qtypes[i%4][0],options:['the passage-supported choice','a broader claim than the passage','an unrelated personal opinion','the opposite conclusion'],correct:0,explain:'正确选项必须能在原文中找到依据；其余选项分别扩大范围、加入个人意见或与原文相反。',tip:'先看题目关键词，再回原文定位。'});}
READINGS=READINGS.concat(generated);
const CONTENT_STATS={vocabulary:WORDS.length,readings:READINGS.length,questions:READINGS.length,levels:READINGS.reduce((a,r)=>(a[r.level]=(a[r.level]||0)+1,a),{})};
